language: java
jdk:
  - oraclejdk8
branches:
  only:
  - master
cache:
  directories:
  - .autoconf
  - $HOME/.m2
before_install:
  - chmod +x mvnw
install:
  - "echo skipped"
script:
  - ./mvnw -Pprod clean package -Dmaven.test.skip=true

after_success:
